### ISSUE TITLE
Some long deps version names gets cut off

### ISSUE THREAD

**Issue by yannbertrand** [VincentHardouin/npm-bump#11]
Long versions names can be stored as shorter than real version name in commit name and markdown output.

Example commit names with Firebase canary :
```
Bump firebase from 16.0-202067221036 to 7.16.0-canary.b07f822b
Bump firebase from 7.16.0 to 7.16.0-202067221036
Bump firebase from .992432e0 to 7.16.0
Bump firebase from 26767cd9 to 7.15.5-canary.992432e0
Bump firebase from 989cb756 to 7.15.5-canary.26767cd9
Bump firebase from cf91 to 7.15.5-canary.989cb756
Bump firebase from .877c060c to 7.15.5-canary.982acf91
```

Example `firebase` markdown output

Package|Old|New
-|-|-
firebase|.877c060c|7.15.5-canary.982acf91
firebase|cf91|7.15.5-canary.989cb756
firebase|989cb756|7.15.5-canary.26767cd9
firebase|26767cd9|7.15.5-canary.992432e0
firebase|.992432e0|7.16.0
firebase|7.16.0|7.16.0-202067221036
firebase|16.0-202067221036|7.16.0-canary.b07f822b

**Comment by VincentHardouin** [comment]
Thanks, this is solved in [0.8.0](https://github.com/VincentHardouin/npm-bump/releases/tag/v0.8.0).
